### ISSUE TITLE
App crashes when in background during id issuing that fails

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#130] opened 2021-12-01 13:15 UTC
**Bug Description**
After issuing an identity that will fail, I moved away from the app, then returned, then moved away again. App was not closed but in background. When returning for the second time, app crashed.

I also submitted a crash report that might have more info.
 
**Steps to Reproduce**
- issue an identity that will fail
- move app to background
- return to app
- (move through tabs)
- move app to background
- return to app
 
**Expected Result**
App opens and shows failed identity + dialog.

**Actual Result**
App crashed. After restart, app shows failed identity card but no dialog is displayed.

**Versions**
- iOS ccd app v1.0.26
- iPhone11
- iOS 14.7.1

**Comment by concordium-cl** [comment] 2022-01-14 07:56
Crashed again when testing in testnet CCD version 1.1.27. Should be tried in newest release.

**Comment by concordium-cl** [comment] 2022-01-27 16:31
@eb-concordium to write comment later.

**Comment by eb-concordium** [comment] 2022-01-27 19:31
I realize now that what happened is not exactly the same. The difference is that I closed the app completely after creating the identity that I would expect to fail. So:

After issuing an identity that will fail, I closed the app completely, then returned and move through, then close app completely. When returning tot the app for the second time (after 10 min or so), app crashed.

**Comment by concordium-cl** [comment] 2022-01-28 08:12
@ruxandra-constantinescu: What was your previous conclusion on this issue? I recall it was not reproducible but I could be wrong.

**Comment by eb-concordium** [comment] 2022-01-28 08:40
I just tried again, but where I instead of closing the app completely just left it open in the background. No crash this time.

**Comment by ruxandra-constantinescu** [comment] 2022-01-28 08:53
@concordium-cl The issue was with a timer that was not stopped when the app went to background. From what I can understand this is slightly different.
@eb-concordium Regarding the crash - when did it crash? Directly when you opened the app, after you typed in the password? Did you submit a crash report by any chance?

**Comment by eb-concordium** [comment] 2022-01-28 09:34
It crashed as the very first thing upon opening the app, if I remember correctly. I did not submit a crash report. I can try again and, if it happens again, submit a crash report.

**Comment by eb-concordium** [comment] 2022-01-28 10:55
I managed to make a failed identity without a crash now, and after I tried to make one again, where the app crashed (where I also submitted a report). I'm not sure if I am completely convinced that it actually crashed because of the failed identity, or if it crashed because I was closing the app and opening it several times (could that cause a crash?).

**Comment by ruxandra-constantinescu** [comment] 2022-01-28 11:04
@eb-concordium I have a crash report now - thank you :) I'm looking into it

**Comment by eb-concordium** [comment] 2022-01-28 12:01
Before closing the app, I was looking at the Accounts screen, yes. But after opening, I don't think I got to see the accounts screen before it crashed. Maybe I should try if I can reproduce it again?

**Comment by ruxandra-constantinescu** [comment] 2022-01-28 12:42
If you have a good way of reproducing, it would be great if you try again. It would be even nicer if you could record it or give a more detailed repro (how many identities you had already, how many accounts, if there are any failed accounts/ids), if you force close open, how long you left it in background, if you tried to refresh, etc). I have tried at least 5 times now to reproduce without success so I think I am missing a step :(

**Comment by eb-concordium** [comment] 2022-01-28 15:33
I sent a video of the crashing to @ruxandra-constantinescu. Let me know, if you need more context :)

**Closed** 2022-01-31 07:55 UTC
Labels: [Type] Bug

**Comment by concordium-cl** [comment] 2022-01-31 09:51
Verified in 1.2.33 by eb. Could not be reproduced.
