### ISSUE TITLE
Unshield problem: The secret to public transfer has an invalid proof

### ISSUE THREAD

**Issue by BeanBagBob** [Concordium/concordium-reference-wallet-ios#232] opened 2022-04-02 10:04 UTC
**Bug Description**
I have an account on the testnet which cannot unshield. The account can send, receive and shield CCDs, but not unshield. All attempts fails with "The secret to public transfer has an invalid proof".
All accounts and IDs validate OK, and there is enough CCDs available on the open balance to do the unshielding.

**Versions**
- Software Version, 2.0.0 (38)
- Mobile device, iPhone 6s

![IMG_0002](https://user-images.githubusercontent.com/73488895/161377911-b2cc7741-fc3d-45ee-9084-9309d6822cb6.jpeg)
![IMG_0003](https://user-images.githubusercontent.com/73488895/161377914-45be26a6-bfa6-4f3c-b334-2cd35cd4666c.jpeg)

**Comment by concordium-cl** [comment] 2022-04-04 06:47
@mh-concordium, can you please look into this issue?

**Comment by mh-concordium** [comment] 2022-04-05 06:27
I will try to reproduce the issue. 
@BeanBagBob Could you please help me a bit?
Do you maybe remember how did you come to this state? 
Did you have an older version and then update Concordium App?
What iOS version are you using?

**Comment by BeanBagBob** [comment] 2022-04-05 07:13
Yes it has been updated from an older version of the wallet at least one time. Running iOS 15.3.1.

**Comment by mh-concordium** [comment] 2022-04-05 07:40
I am looking at the issue but I can't reproduce it with these steps:
1. Install 1.3 version and create new ID and Initial account
2. Request 200CCDs for test.
3. Shield 25 CCDs and repeat that for 4 times so that total amount of shielded CCDs is 100. This way, transaction details list will have 4 inputs.
4. Close the app.
5. Upgrade to 2.0.0 (38).
6. Start the app and insert wallet password.
7. Unshield 25 CCDs.

Looks ok.

Did you maybe use Make backup -> Restore backup in any case?

**Comment by mh-concordium** [comment] 2022-04-05 08:06
If you have time available and you are willing to help, could you provide the steps as I did above? It would be very much appreciated and it would help in attempt to recreate the issue.

When you say upgraded from previous version which one is the previous one?

Comparation you use with "old" and "new" accounts, what is old account and what is new? I guess new is just the account created in 2.0.0 (38)?

**Comment by BeanBagBob** [comment] 2022-04-05 08:45
I don't know the exact versions before the update to 2.0.0. But I have been updating as new versions came out.
- "New accounts" = created on 2.0.0.
- "Old accounts" = created before 2.0.0. Not sure about the app versions. But.. the two accounts that fails to unshield were created on 2022-01-30 and 2022-02-05 respectively on whatever version was newest at the time.

I will try to follow your steps.

**Comment by mh-concordium** [comment] 2022-04-05 08:56
Did you at any point in time tried to restore the iPhone from iCloud?
I am asking that because we had an issue that might be related.

**Comment by BeanBagBob** [comment] 2022-04-05 08:59
Ok. I created a new export, reinstalled 2.0.0, imported the backup and now unshielding works again...

Do you still want me to recreate your steps?

No restores from iCloud (and one of the iPhones was factory reset just before the wallet was installed).

**Comment by mh-concordium** [comment] 2022-04-05 09:03
I was thinking the steps to the state where it actually fails to unsheald. Like the steps to the error message "The secret to public transfer has an invalid proof".

**Comment by BeanBagBob** [comment] 2022-04-05 09:35
I followed your steps, but I can't reproduce the error. I also tried with version 1.2 (28) instead of 1.3, and it also works.

And as mentioned earlier, after importing a backup, the account that initially had problems can now unshield again.

On the second phone I still have an account that cannot unshield. I guess it also works after importing a backup, but I haven't done that yet if you want me to test something.

**Comment by mh-concordium** [comment] 2022-04-05 12:22
Okay, I would say we should close the issue since we can't clearly reproduce this issue and come to the state where you got the error as you initially wrote "The secret to public transfer has an invalid proof".  Also in relation to that, we had an issue that sounds to me somewhat similar because user was loosing the keys to the wallet in the case of factory reset from iOS cloud. [[Keys do not work](https://github.com/Concordium/concordium-reference-wallet-ios/issues/173)] In any case, if the original backup file is valid and backup password is remembered, user can always access the funds.

Overall, I want to thank you very much for your assistance and will to commit the time to help me in attempt to reproduce the issue.

**Closed by mh-concordium** 2022-04-05 12:22 UTC

**Comment by BeanBagBob** [comment] 2022-04-05 15:52
I agree.

For good measure I tested restoring on the second iPhone, and unshielding works there as well now.
Note: The backup was created seconds before deleting the app, so here the keys were not lost in a cloud restore.
