### ISSUE TITLE
Support for more identity providers

### ISSUE THREAD

**Issue by concordium-cl** [Concordium/concordium-reference-wallet-ios#87] opened 2021-11-01 10:29 UTC
**Task description**
Add support for another identity provider.

**Sub-tasks**
- [ ] change hardcoded contact info in support dialog when id fails (wallet-proxy)
- [ ] potential changes to id flow?

**Comment by jens-concordium** [comment] 2021-11-26 11:45
@concordium-cl, this looks good to me on iOS 15 in v1.0(25). Even old failed identities work as intended, if they are kept in app through the update to 1.0(25).

**Comment by concordium-cl** [comment] 2021-11-26 13:06
@jens-concordium, not sure how to test it atm?

**Comment by jens-concordium** [comment] 2021-11-26 13:08
@concordium-cl I just made sure that it still works for Notabene, not much else we can do atm. At least we can tell that the info from the wallet-proxy is presented correctly from Notabene. 

You can also make some failed identities in previous versions of the app, and leave them in there while updating to the new version, to see what happens with them.

**Comment by td202** [comment] 2021-11-26 16:07
On the display for a failed identity, it is currently hardcoded with the Notabene info. This is fixed by #122.

**Comment by jens-concordium** [comment] 2021-11-29 12:14
@td202, oh so this was not included in the latest build?

**Comment by concordium-cl** [comment] 2021-12-01 12:49
Reopened, as new PRs are linked.

**Closed** 2021-12-03 13:34 UTC
Labels: [Prio] Medium, [Type] Task
